### ISSUE TITLE
file does not load

### ISSUE THREAD

**Issue by vladimirias** [michaelt/martin-lof#12]
An-Intuitionistic-Theory-of-Types-1972.pdf does not load.

**Comment by michaelt** [comment]
I think it is too big for github to be willing to render, or have rendered. (It looks terrible if I open with my browser; but fine in my regular pdf reader).  The links in the readme prompt direct download of the file https://github.com/michaelt/martin-lof prompt downloading.  We revised the setup a while ago, when, if I remember, github wouldn't even attempt to render the file. Maybe it needs to be rethought.

**Comment by vladimirias** [comment]
May be we should ask Per to submit everything to the arXiv? We could help him with the actual submission. I hope that arXiv would make an exception from their general rule and accept pdfs without the sources.

Vladimir.

**Comment by michaelt** [comment]
Obviously that would be ideal!

It occurs to me that something like the present arrangement might be more user-friendly if @stevana  @gallais and other contributors made an "organization" on github, `archive-pml` or the like. 

Then I think we could use the github pages machinery which would permit serving pdfs in a more standard user-intelligible way: the main index.html page would be like the current readme, etc. I did something like this once before, but the mechanism has changed, and might involve a slightly delicate use of git. 

This accumulation of non-text files is of course an odd use of version control; it makes sense, though, since 'revision' is only by accretion and it is very easy for people to alter.

**Comment by michaelt** [comment]
Actually it's pretty easy.  Pardon the lame "organization" name and page-styling, but http://archive-pml.github.io/ just serves from https://github.com/archive-pml/archive-pml.github.io  In that particular context links to pdfs and other binary nonsense are respected. This suggests various better plans, but for the moment I think I will just make the links on the present readme point there.

**Comment by michaelt** [comment]
Right, so now the links from the readme point to properly served files. No doubt a better arrangement can be thought up. Thanks.
